const styles = {
  appContainer: {
    height: '133.3333vh',
    width: '133.3333vw',
    display: 'flex',
    flexDirection: 'column',
    fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    overflow: 'hidden',
  },

  // ── Header ──────────────────────────────────────────────────────────────────
  header: {
    height: 60,
    backgroundColor: '#fff',
    borderBottom: '3px solid #9F2241',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 20px',
    zIndex: 1000,
  },
  headerLeft:    { display: 'flex', alignItems: 'center', gap: 15 },
  logo:          { height: 45 },
  headerTitles:  { display: 'flex', flexDirection: 'column' },
  headerTitle:   { fontSize: 14, fontWeight: 700, color: '#9F2241' },
  headerSubtitle:{ fontSize: 11, color: '#666' },
  headerRight:   { display: 'flex', alignItems: 'center' },
  userName:      { fontSize: 14, color: '#333' },

  // ── Toolbar ─────────────────────────────────────────────────────────────────
  toolbar: {
    position: 'fixed',
    left: 0,
    top: 60,
    bottom: 0,
    width: 55,
    backgroundColor: '#6B1C3A',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    paddingTop: 15,
    gap: 8,
    zIndex: 1000,
  },
  toolbarBtn: {
    width: 44,
    height: 44,
    border: 'none',
    borderRadius: 8,
    backgroundColor: 'transparent',
    color: 'rgba(255,255,255,0.7)',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s ease',
  },
  toolbarBtnActive: { backgroundColor: '#967440', color: '#fff' },

  // ── Dropdown ─────────────────────────────────────────────────────────────────
  dropdownMenu: {
    position: 'absolute',
    left: 55,
    top: 0,
    backgroundColor: '#fff',
    borderRadius: 8,
    boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
    padding: '8px 0',
    display: 'flex',
    flexDirection: 'column',
    minWidth: 160,
    zIndex: 2000,
    border: '1px solid rgba(0,0,0,0.1)',
  },
  dropdownItem: {
    padding: '10px 16px',
    fontSize: 13,
    color: '#333',
    cursor: 'pointer',
    backgroundColor: 'transparent',
    border: 'none',
    textAlign: 'left',
    width: '100%',
    transition: 'background 0.2s',
  },

  // ── Map wrapper ───────────────────────────────────────────────────────────────
  mapWrapper:  { flex: 1, marginLeft: 55, position: 'relative' },
  mapLoading: {
    position: 'absolute',
    top: 20,
    left: '50%',
    transform: 'translateX(-50%)',
    backgroundColor: 'rgba(0,0,0,0.8)',
    color: '#fff',
    padding: '12px 24px',
    borderRadius: 8,
    zIndex: 500,
    display: 'flex',
    alignItems: 'center',
    gap: 10,
  },
  spinner: {
    width: 20,
    height: 20,
    border: '2px solid rgba(255,255,255,0.3)',
    borderTopColor: '#fff',
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
  coordsDisplay: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    backgroundColor: 'rgba(107, 28, 58, 0.9)',
    color: '#fff',
    padding: '8px 14px',
    borderRadius: 4,
    fontSize: 13,
    fontFamily: 'monospace',
    zIndex: 100,
  },
  cameraCount: {
    position: 'absolute',
    top: 20,
    right: 60,
    backgroundColor: '#fff',
    color: '#333',
    padding: '10px 16px',
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 600,
    boxShadow: '0 2px 8px rgba(0,0,0,0.15)',
    display: 'flex',
    alignItems: 'center',
    zIndex: 100,
  },

  // ── Floating Panel ────────────────────────────────────────────────────────────
  floatingPanel: {
    position: 'fixed',
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    backdropFilter: 'blur(8px)',
    WebkitBackdropFilter: 'blur(8px)',
    borderRadius: 12,
    boxShadow: '0 8px 32px rgba(0,0,0,0.2)',
    zIndex: 900,
    overflow: 'hidden',
    border: '1px solid rgba(255, 255, 255, 0.3)',
  },
  panelHeader: {
    backgroundColor: '#6B1C3A',
    color: '#fff',
    padding: '12px 16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    cursor: 'grab',
    userSelect: 'none',
  },
  panelHeaderLeft:   { display: 'flex', alignItems: 'center', gap: 10 },
  panelIcon:         { opacity: 0.9 },
  panelTitle:        { fontSize: 14, fontWeight: 600 },
  panelHeaderButtons:{ display: 'flex', gap: 4 },
  panelBtn: {
    background: 'none',
    border: 'none',
    color: 'rgba(255,255,255,0.8)',
    cursor: 'pointer',
    padding: 4,
    borderRadius: 4,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  panelContent: { padding: 16, overflowY: 'auto', maxHeight: 'calc(100vh - 200px)' },

  // ── Panel sections ────────────────────────────────────────────────────────────
  panelSection: { display: 'flex', flexDirection: 'column', gap: 12 },
  sectionTitle: { fontSize: 13, fontWeight: 600, color: '#333', margin: 0, paddingBottom: 8, borderBottom: '1px solid #eee' },
  divider:      { height: 1, backgroundColor: '#eee', margin: '8px 0' },

  // ── Checkboxes ────────────────────────────────────────────────────────────────
  checkboxGrid: { display: 'flex', flexDirection: 'column', gap: 6 },
  checkboxItem: { display: 'flex', alignItems: 'center', gap: 8, cursor: 'pointer', padding: '4px 0' },
  checkbox:     { width: 16, height: 16, cursor: 'pointer' },
  checkboxLabel:{ fontSize: 13, color: '#444' },
  colorDot:     { width: 12, height: 12, borderRadius: '50%', flexShrink: 0 },

  // ── Search ────────────────────────────────────────────────────────────────────
  searchBox:   { position: 'relative', marginBottom: 8 },
  searchIcon:  { position: 'absolute', left: 10, top: '50%', transform: 'translateY(-50%)', color: '#999' },
  searchInput: { width: '100%', padding: '10px 10px 10px 38px', border: '1px solid #ddd', borderRadius: 8, fontSize: 13, outline: 'none', boxSizing: 'border-box' },

  // ── Lists ─────────────────────────────────────────────────────────────────────
  alcaldiasList: { maxHeight: 250, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: 4 },

  // ── Map style buttons ─────────────────────────────────────────────────────────
  mapStyleGrid:      { display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 8 },
  mapStyleBtn: {
    padding: '12px 16px',
    border: '2px solid #ddd',
    borderRadius: 8,
    backgroundColor: '#fff',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 500,
    transition: 'all 0.2s',
  },
  mapStyleBtnActive: { borderColor: '#9F2241', backgroundColor: 'rgba(159, 34, 65, 0.1)', color: '#9F2241' },

  // ── Input groups ──────────────────────────────────────────────────────────────
  inputGroup: { display: 'flex', flexDirection: 'column', gap: 4 },
  inputLabel: { fontSize: 12, fontWeight: 500, color: '#666' },
  textInput:  { padding: '10px 12px', border: '1px solid #ddd', borderRadius: 8, fontSize: 14, outline: 'none' },

  // ── Buttons ───────────────────────────────────────────────────────────────────
  primaryBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '12px 16px',
    backgroundColor: '#9F2241',
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 500,
    cursor: 'pointer',
    marginTop: 8,
  },
  clearBtn: {
    padding: '10px 16px',
    backgroundColor: '#f5f5f5',
    color: '#666',
    border: '1px solid #ddd',
    borderRadius: 8,
    fontSize: 13,
    cursor: 'pointer',
  },
  applyBtn: {
    padding: '10px 16px',
    backgroundColor: 'rgb(243, 222, 222)',
    color: '#9F2241',
    border: '1px solid #ddd',
    borderRadius: 8,
    fontSize: 13,
    cursor: 'pointer',
  },
   applyBtn2: {
    padding: '10px 16px',
    backgroundColor: '#a2f1bd',
    color: '#0d8a37',
    border: '1px solid #ddd',
    borderRadius: 8,
    fontSize: 13,
    cursor: 'pointer',
  },
  downloadBtn: {
    padding: '10px 16px',
    backgroundColor: '#2E7D32',
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    fontSize: 13,
    cursor: 'pointer',
    marginTop: 8,
  },
  btnMaps: {
    display: 'block',
    backgroundColor: '#28a745',
    color: 'white',
    textAlign: 'center',
    padding: '8px',
    borderRadius: '4px',
    textDecoration: 'none',
    fontWeight: 'bold',
    fontSize: '13px',
    margin: '0 8px 8px 8px',
  },

  // ── Marker info ───────────────────────────────────────────────────────────────
  markerInfo: { padding: '10px 12px', backgroundColor: '#f0f9ff', borderRadius: 8, fontSize: 12, color: '#0369a1', marginTop: 8 },

  // ── Table ─────────────────────────────────────────────────────────────────────
  tableWrapper: { overflowX: 'auto' },
  table:        { width: '100%', borderCollapse: 'collapse', fontSize: 12 },
  th:           { backgroundColor: '#9F2241', color: '#fff', padding: '10px 12px', textAlign: 'left', fontWeight: 600 },
  td:           { padding: '10px 12px', borderBottom: '1px solid #eee' },
  totalRow:     { backgroundColor: '#f5f5f5', fontWeight: 600 },

  // ── States ────────────────────────────────────────────────────────────────────
  loading:    { padding: 20, textAlign: 'center', color: '#666' },
  emptyState: { padding: 20, textAlign: 'center', color: '#999', fontSize: 13 },

  // ── Popups ────────────────────────────────────────────────────────────────────
  popupTable:    { width: '100%', borderCollapse: 'collapse', marginTop: '4px', marginBottom: '12px' },
  popupTdLabel:  { fontWeight: 'bold', fontSize: '12px', color: '#333', padding: '6px 8px', borderBottom: '1px solid #ddd', borderRight: '1px solid #ddd', borderLeft: '1px solid #ddd', width: '35%', backgroundColor: '#f9f9f9' },
  popupTdValue:  { fontSize: '12px', color: '#555', padding: '6px 8px', borderBottom: '1px solid #ddd', borderRight: '1px solid #ddd' },
  popupHeader:   { backgroundColor: '#6B1C3A', color: '#ffffff', fontWeight: 'bold', textAlign: 'center', padding: '8px', fontSize: '14px' },
  popupContent:  {},

  // ── Poly Popup ────────────────────────────────────────────────────────────────
  polyPopupContent: { display: 'flex', flexDirection: 'column', width: '230px', maxHeight: '320px', overflowY: 'auto' },
  polyPopupHeader:  { color: '#ffffff', padding: '10px 14px', display: 'flex', flexDirection: 'column', gap: 3 },
  polyPopupTipo:    { fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.07em', opacity: 0.82 },
  polyPopupNombre:  { fontSize: 15, fontWeight: 700, lineHeight: 1.25 },

  // ── Measurement Panel ─────────────────────────────────────────────────────────
  measureResultCard: { padding: '12px', backgroundColor: '#f8fafc', borderRadius: '10px', border: '1px solid #e2e8f0', display: 'flex', flexDirection: 'column', gap: '4px' },
  measureLabel:      { fontSize: '11px', fontWeight: '700', color: '#64748b', textTransform: 'uppercase', letterSpacing: '0.05em' },
  measureValue:      { fontSize: '20px', fontWeight: '800', color: '#1e293b', fontFamily: 'monospace' },
  measureUnit:       { fontSize: '12px', fontWeight: '500', color: '#94a3b8' },
  toolBtn: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '10px 4px',
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
};

export default styles;